name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

dependencies:
  dart_firebase_admin: ^0.3.0
  dartblaze: ^0.0.1
  functions_framework: ^0.4.0
  http: ^1.0.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4

  # json
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.0.0
  dartblaze_builder: ^0.0.1+1
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  test: ^1.15.7
