name: dartblaze_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

dependencies:
  analyzer: ">=5.12.0 <7.0.0"
  build: ^2.0.0
  build_config: ">=0.4.3 <2.0.0"
  dartblaze:
    path: ../dartblaze
  dartblaze_core:
    path: ../dartblaze_core
  dart_style: ^2.0.0
  functions_framework: ^0.4.3+1
  meta: ^1.2.4
  path: ^1.9.0
  source_gen: ^1.0.0
  glob: ^2.1.2

dev_dependencies:
  test: ^1.24.0
