name: dartblaze_builder
description: Code generator for DartBlaze.
version: 0.0.1+1
repository: https://github.com/dinko7/dartblaze
homepage: https://dartblaze.com/

environment:
  sdk: ^3.6.0
resolution: workspace

dependencies:
  analyzer: ">=5.12.0 <7.0.0"
  build: ^2.0.0
  build_config: ">=0.4.3 <2.0.0"
  dartblaze: ^0.0.1
  dartblaze_shared:
    path: ../dartblaze_shared
  dart_style: ^2.0.0
  shelf: ^1.4.2
  functions_framework: ^0.4.3+1
  meta: ^1.2.4
  path: ^1.9.0
  source_gen: ^1.0.0
  glob: ^2.1.2
  collection: ^1.19.1

dev_dependencies:
  test: ^1.24.0
