name: dartblaze_core
description: Core components shared between DartBlaze packages.
version: 0.0.1
repository: https://github.com/dinko7/dartblaze
homepage: https://dartblaze.com/

environment:
  sdk: ^3.4.1

dependencies:
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
